{% set name = "click-option-group" %}
{% set version = "0.5.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8dc780be038712fc12c9fecb3db4fe49e0d0723f9c171d7cda85c20369be693c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - click >=7.0,<9
    - python >=3.6,<4.0

test:
  imports:
    - click_option_group
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/click-contrib/click-option-group
  summary: Option groups missing in Click
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SimonBoothroyd
    - sodre
