{% set name = "click-option-group" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6e924f3c46b657feb5b72679f7e930f8e5b224b766ab35c91ae4019b4e0615e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - click >=7.0,<9
    - python >=3.6,<4.0

test:
  imports:
    - click_option_group
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/click-contrib/click-option-group
  summary: Option groups missing in Click
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sodre
